// Rounds built from the teacher's picks by pamokos-vaikams/tikra-ar-ai-select/build_game.py
window.ROUNDS = [
 [
  {
   "file": "media/v2-01-sesi-pirstai.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Suskaičiuok pirštus: jų šeši! Dirbtinis intelektas dažnai klysta piešdamas rankas.",
   "author": "Stable Diffusion 1.5, prompted by Corvus",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:AI_generated_hand.png",
   "generator": "Stable Diffusion 1.5",
   "note": "Kept from v1 (item 01).",
   "has_audio": ""
  },
  {
   "file": "media/v2-02-suo-futbolininkas.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Šis šuo Stambule atbėgo į futbolo aikštę ir pats varinėjo kamuolį. Gal jį pakvies į rinktinę?",
   "author": "CeeGee",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:FootballerDog_(2).jpg",
   "generator": "",
   "note": "Nikon D5100 EXIF 2018-01-07. Fatih Mimar Sinan Stadium, Istanbul.",
   "has_audio": ""
  },
  {
   "file": "media/v3-03-korgis-vlogeris.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Šuo nemoka laikyti asmenukių lazdos! Šį filmuką Sora sukūrė iš vieno sakinio apie šunį tinklaraštininką.",
   "author": "OpenAI Sora",
   "license": "Public domain (PD-algorithm)",
   "license_url": "",
   "source_url": "https://web.archive.org/web/20240216001508/https://openai.com/sora",
   "generator": "OpenAI Sora (2024)",
   "note": "Official Sora showcase, prompt \"A corgi vlogging itself in tropical Maui.\" File: https://cdn.openai.com/sora/videos/vlogger-corgi.mp4. First 10 s. Edges cropped 12% to remove the SORA watermark.",
   "has_audio": ""
  },
  {
   "file": "media/v3-02-futbolas-gulomis.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Tai laisvojo stiliaus futbolas. Žaidėjas žongliruoja kamuoliu net gulėdamas ant nugaros.",
   "author": "Marie-Lan Nguyen",
   "license": "CC BY 2.5",
   "license_url": "https://creativecommons.org/licenses/by/2.5",
   "source_url": "https://commons.wikimedia.org/wiki/File:Football_freestyle_2013_Masters_epee_t171023.jpg",
   "generator": "",
   "note": "Nikon D800E EXIF 2013-12-01. Small Nike logos on ball and shoes, not the focus.",
   "has_audio": ""
  },
  {
   "file": "media/v2-05-robotu-futbolas.mp4",
   "answer": "real",
   "kind": "video",
   "tell_lt": "Tikra! Tai RoboCup, robotų futbolo čempionatas Leipcige. Robotus užprogramuoja studentai, o per rungtynes jie žaidžia patys, be pultelio.",
   "author": "Ubahnverleih",
   "license": "CC0",
   "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
   "source_url": "https://commons.wikimedia.org/wiki/File:Robocup_2016_-_UChile_vs_HTWK_Leipzig_(3).ogv",
   "generator": "",
   "note": "Cut 2-12 s from the 17 s original. Nao robots, UChile vs HTWK Leipzig.",
   "has_audio": ""
  },
  {
   "file": "media/v2-07-dailiaciuoze-su-kate.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Perskaityk reklamas ant bortelio: raidės sumaišytos į košę. O kokia katė leistųsi vežiojama ant galvos per šuolį?",
   "author": "Sora 2 / OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:OpenAI_-_This_is_Sora_2.webm",
   "generator": "OpenAI Sora 2 (2025)",
   "note": "Cut 2.95-12.75 s from the Sora 2 launch compilation. Prompt: 'figure skater performs a triple axle with a cat on her head'.",
   "has_audio": ""
  },
  {
   "file": "media/v2-06-ozkos-medyje.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Maroke ožkos įlipa į argano medžius ir skabo jų vaisius. Ožka medyje, o ne paukštis!",
   "author": "Grand Parc - Bordeaux, France",
   "license": "CC BY 2.0",
   "license_url": "https://creativecommons.org/licenses/by/2.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Goats_in_an_argan_tree.jpg",
   "generator": "",
   "note": "Canon EOS 5D Mark II EXIF 2013-06-18. Essaouira, Morocco.",
   "has_audio": ""
  },
  {
   "file": "media/v2-09-vaikai-prie-kompiuterio.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Pažiūrėk į dešinį kompiuterį: vietoj obuoliuko ten keistas vabalas. O visi trys vaikai spokso į tave vienodu žvilgsniu.",
   "author": "Ziko",
   "license": "CC0",
   "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
   "source_url": "https://commons.wikimedia.org/wiki/File:2024-07_SD_ZvD_three_children_at_a_computer.png",
   "generator": "Nenurodytas (failo pavadinime SD, tikriausiai Stable Diffusion)",
   "note": "File page description: 'Three children at a computer, AI image'.",
   "has_audio": ""
  },
  {
   "file": "media/v2-08-kiauliu-lenktynes.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Anglijos ūkyje vyksta kiaulių lenktynės su kliūtimis. Kiaulės net turi savo spalvotus marškinėlius.",
   "author": "AngusMurray1989",
   "license": "CC0",
   "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
   "source_url": "https://commons.wikimedia.org/wiki/File:Pig_racing_at_Pennywell_Farm.jpg",
   "generator": "",
   "note": "Nikon D90 EXIF 2012-04-02. Pennywell Farm, Devon.",
   "has_audio": ""
  },
  {
   "file": "media/v2-12-katinas-lovoje.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Stebėk katino letenas. Viena letena staiga atsiranda iš niekur.",
   "author": "Sora/OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Cat-on-bed.webm",
   "generator": "OpenAI Sora (2024)",
   "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly. Kept from v1 (item 09).",
   "has_audio": ""
  },
  {
   "file": "media/v2-13-dviraciu-futbolas.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Tai dviračių futbolas. Kamuolį muša ne kojomis, o dviračio ratu!",
   "author": "Kurukuruback",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Corner_kick_of_cycle-ball.jpg",
   "generator": "",
   "note": "Nikon D200 EXIF 2007-07-08. Japan.",
   "has_audio": ""
  },
  {
   "file": "media/v2-15-vaiku-futbolo-treniruote.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Pažiūrėk į berniuką kairėje: jo ranka išlenda tiesiai pro marškinėlius. O vaikų pirštai keistai susilieję.",
   "author": "CANVA (uploaded by Commons user)",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:%D9%85%D8%AF%D8%B1%D8%A8_%D9%83%D8%B1%D8%A9_%D8%A7%D9%84%D9%82%D8%AF%D9%85_%D9%8A%D9%82%D9%88%D9%85_%D8%A8%D8%AA%D8%AF%D8%B1%D9%8A%D8%A8_%D8%A7%D9%84%D9%84%D8%A7%D8%B9%D8%A8%D9%8A%D9%86_%D8%B7%D8%B1%D9%8A%D9%82%D8%A9_%D8%A7%D9%84%D8%AA%D8%B3%D8%AF%D9%8A%D8%AF.jpg",
   "generator": "Canva AI (modelis nenurodytas)",
   "note": "File page marks it AI (Restrictions: ai; categories AI-generated association football, AI misgeneration). EXIF Software: Canva.",
   "has_audio": ""
  },
  {
   "file": "media/v3-09-motociklininkas-supermenas.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Motociklininkas ore paleidžia motociklą ir skrenda kaip supermenas. Po akimirkos jis vėl sugriebia vairą.",
   "author": "Stefan Krause, Germany",
   "license": "CC BY-SA 3.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Freestyle_Motocross_1.jpg",
   "generator": "",
   "note": "Nikon D80 EXIF 2008-04-27. Trick: Superman seat grab. KTM stickers on the bike, not the focus.",
   "has_audio": ""
  },
  {
   "file": "media/v3-11-suo-prie-kompiuterio.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Pažiūrėk į šuns kaklą: antkaklis keistai susipynęs su kailiu. O ekrane raidės neįskaitomos.",
   "author": "Lwneal",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Example-dog-on-the-internet.png",
   "generator": "Stable Diffusion",
   "note": "Prompt: \"Cinematic photo of a dog on the Internet editing Wikipedia\", seed 3219238372.",
   "has_audio": ""
  },
  {
   "file": "media/v2-14-bezdziones-pirtyje.mp4",
   "answer": "real",
   "kind": "video",
   "tell_lt": "Tikra! Japonijoje beždžionės žiemą maudosi karštose versmėse, kad sušiltų. Tikras beždžionių SPA!",
   "author": "Nesnad",
   "license": "CC BY-SA 3.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Jigokudani_Monkey_Park_-_hotsprings.ogv",
   "generator": "",
   "note": "Original is 4.97 s; slowed to 0.9x speed (5.5 s) to meet the 5 s minimum.",
   "has_audio": ""
  },
  {
   "file": "media/v2-18-triusiai.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Failas vadinasi „Trys triušiai“, o jų keturi! Ir visi kaip nukopijuoti: tos pačios ausys, tas pats snukutis.",
   "author": "Fooocus, prompted by Commons user",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:SD_-_Three_Rabbits.png",
   "generator": "Stable Diffusion XL (Fooocus)",
   "note": "Uploaded to show AI limitations (AI Art Generation Handbook, Wikibooks).",
   "has_audio": ""
  },
  {
   "file": "media/v3-08-zebrazirafe.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Zebražirafių nėra! Pažiūrėk į ausis: jos spalvotos lyg plastikinės.",
   "author": "OpenAI DALL-E 2",
   "license": "Public domain (PD-algorithm)",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:A_new_hybrid_species_%22Zebra-Giraffe%22_spotted_in_African_Safari_during_golden_hour.jpg",
   "generator": "DALL-E 2",
   "note": "Prompt: \"A new hybrid species Zebra-Giraffe spotted in African Safari during golden hour\". Bottom strip with the DALL-E colour bar cropped.",
   "has_audio": ""
  },
  {
   "file": "media/v2-19-kates-suolis.mp4",
   "answer": "real",
   "kind": "video",
   "tell_lt": "Tikra! Katės kūnas lankstus kaip spyruoklė, todėl ji nušoka taip toli. Filmukas sulėtintas, kad matytum visą skrydį.",
   "author": "Record 124 (Vimeo)",
   "license": "CC BY 3.0",
   "license_url": "https://creativecommons.org/licenses/by/3.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Salto_-_Cat_Jump.webm",
   "generator": "",
   "note": "Imported from Vimeo (2017), license reviewed by bot. No camera EXIF; 2017 predates AI video generators. Cut 1.0-9.5 s.",
   "has_audio": ""
  }
 ],
 [
  {
   "file": "media/v2-03-mamutai.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Mamutai išnyko prieš tūkstančius metų. Niekas negalėjo jų nufilmuoti.",
   "author": "Sora / OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Wooly_Mammoth_by_OpenAI_Sora.webm",
   "generator": "OpenAI Sora (2024)",
   "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly. Kept from v1 (item 04).",
   "has_audio": ""
  },
  {
   "file": "media/v1-02-melynas-omaras.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikras! Maždaug vienas omaras iš dviejų milijonų gimsta mėlynas.",
   "author": "EgorovaSvetlana",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Blue_Lobster_Woods_Hole_Science_Aquarium.jpg",
   "generator": "",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v2-21-dalmatinas-palangeje.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Labai sunku! Šį filmuką sukūrė Sora. Stebėk, kaip šuo pereina nuo vieno lango prie kito: ar ten iš viso yra kur pastatyti kojas?",
   "author": "Sora / OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Open_AI_Sora_in_Action-_Italian_Pup.webm",
   "generator": "OpenAI Sora (2024)",
   "note": "Original from openai.com/sora (Feb 2024). Edges cropped 5% to remove the Sora watermark.",
   "has_audio": ""
  },
  {
   "file": "media/v3-15-zmogus-ant-vandens-sroves.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Vyras stovi ant lentos, kurią aukštyn kelia vandens srovės. Tai vadinama flyboard.",
   "author": "Monmar Comunicació from Vic",
   "license": "CC BY-SA 2.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/2.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Flyboard_during_Sal%C3%B3_N%C3%A0utic_Internacional_de_Barcelona_2012_(36329436412).jpg",
   "generator": "",
   "note": "Canon EOS 5D Mark II EXIF 2012-09-26, Barcelona boat show. Cropped around the rider.",
   "has_audio": ""
  },
  {
   "file": "media/v2-10-kaciukas-ir-anciukai.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Ančiukų snapai ir kojos atrodo kaip rožinis plastikas.",
   "author": "matankic",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Ducklings_and_kittens_play_super_cute_high_resulotion.png",
   "generator": "DALL-E (2022), vėliau taisyta GIMP",
   "note": "Kept from v1 (item 07).",
   "has_audio": ""
  },
  {
   "file": "media/v2-17-drambliu-polo.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Nepale žaidžiamas dramblių polo. Žaidėjai sėdi ant dramblių ir muša kamuolį ilga lazda.",
   "author": "Pratap Baniya",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Elephant_Polo_Sauraha_Chitwan_2018_(1).jpg",
   "generator": "",
   "note": "Nikon D7000 EXIF 2018-12-28. Sauraha, Chitwan, Nepal.",
   "has_audio": ""
  },
  {
   "file": "media/v1-13-meska-geles.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Gėlės aplink mešką sudėliotos per gražiai. Kailis atrodo lyg nupieštas teptuku.",
   "author": "Kandukuru Nagarjun from Bangalore, India",
   "license": "CC BY 2.0",
   "license_url": "https://creativecommons.org/licenses/by/2.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:An_Asian_black_bear_amidst_mahua_flowers_(52842957476).png",
   "generator": "Midjourney (2023)",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v2-24-bezdziones-asmenuke.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikra! Šią asmenukę padarė pati beždžionė, paspaudusi fotografo kamerą. Teismai net ginčijosi, kam priklauso nuotrauka.",
   "author": "Pati beždžionė (Macaca nigra), fotografo Davido Slaterio kamera",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Macaca_nigra_self-portrait_large.jpg",
   "generator": "",
   "note": "PD-animal on Commons. EXIF DateTimeOriginal 2011-07-04. Famous 'monkey selfie' copyright dispute.",
   "has_audio": ""
  },
  {
   "file": "media/v1-24-karunuotasis-balandis.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Toks paukštis tikrai yra, tai karūnuotasis balandis. Bet šį filmuką sukūrė Sora.",
   "author": "Sora/OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Victoria-crowned-pigeon.webm",
   "generator": "OpenAI Sora (2024)",
   "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly.",
   "has_audio": ""
  },
  {
   "file": "media/v1-03-rozinis-ezeras.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikras! Šis ežeras Australijoje rožinis dėl mažyčių dumblių ir druskos.",
   "author": "Aussie Oc",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Lake_Hillier_2_Middle_Island_Recherche_Archipelago_NR_IV-2011.JPG",
   "generator": "",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v3-21-tetis-ir-sunus.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Labai sunku! Viskas per švaru ir per tvarkinga, lyg reklamoje. Tokius veidus dirbtinis intelektas jau piešia labai gerai.",
   "author": "U3260357",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Boy_and_dad.png",
   "generator": "nenurodyta (Commons kategorija: AI-generated facial expressions)",
   "note": "Labelled AI only by the Commons category; generator not named. Fictional people.",
   "has_audio": ""
  },
  {
   "file": "media/v1-14-vaivorykstinis-eukaliptas.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikras! Šio medžio žievė lupasi, o po ja matosi žalia, oranžinė ir violetinė.",
   "author": "Forest and Kim Starr",
   "license": "CC BY 3.0 us",
   "license_url": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
   "source_url": "https://commons.wikimedia.org/wiki/File:Starr-090618-1062-Eucalyptus_deglupta-trunk_and_bark-Hana_Hwy-Maui_(24670004300).jpg",
   "generator": "",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v1-10-levandu-ledai.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Viskas per tobula. Visi rutuliai vienodi, o žiedeliai išdėlioti lyg ranka.",
   "author": "SNRTZ",
   "license": "CC BY-SA 4.0",
   "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
   "source_url": "https://commons.wikimedia.org/wiki/File:Levendul%C3%A1s_fagylalt.png",
   "generator": "nežinomas (įkėlėjas pažymėjo kaip AI)",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v1-20-romaninis-brokolis.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikras! Šis brokolis sudarytas iš bokštelių, kurie kartojasi vis mažesni.",
   "author": "Richard Bartz, Munich aka Makro Freak",
   "license": "CC BY-SA 2.5",
   "license_url": "https://creativecommons.org/licenses/by-sa/2.5",
   "source_url": "https://commons.wikimedia.org/wiki/File:Romanesco_Brassica_oleracea_Richard_Bartz.jpg",
   "generator": "",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v1-19-zalias-obuolys.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Beveik neįmanoma atskirti! Net paprastas obuolys gali būti netikras.",
   "author": "Midjourney; prompted by The masketta man",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Green_apple_gen.png",
   "generator": "Midjourney v6",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v1-08-druskos-veidrodis.jpg",
   "answer": "real",
   "kind": "image",
   "tell_lt": "Tikras! Bolivijoje yra didžiulė druskos lyguma. Po lietaus ji tampa veidrodžiu.",
   "author": "Luca Galuzzi (Lucag)",
   "license": "CC BY-SA 2.5",
   "license_url": "https://creativecommons.org/licenses/by-sa/2.5",
   "source_url": "https://commons.wikimedia.org/wiki/File:Watching_Sunset_Salar_de_Uyuni_Bolivia_Luca_Galuzzi_2006.jpg",
   "generator": "",
   "note": "",
   "has_audio": ""
  },
  {
   "file": "media/v1-22-slenis-su-nameliu.jpg",
   "answer": "ai",
   "kind": "image",
   "tell_lt": "Sunku! Pažiūrėk į akmenis upėje. Jie išrikiuoti per tvarkingai.",
   "author": "VulcanSphere",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Illuminated_Valley_in_the_Afternoon_(Imagen_4.0).webp",
   "generator": "Google Imagen 4.0 (Gemini)",
   "note": "Bottom-right Gemini watermark cropped out.",
   "has_audio": ""
  },
  {
   "file": "media/v1-17-uolu-pakrante.mp4",
   "answer": "ai",
   "kind": "video",
   "tell_lt": "Labai sunku! Šį vaizdą sukūrė Sora iš vieno sakinio, o ne dronas.",
   "author": "Sora/OpenAI",
   "license": "Public domain",
   "license_url": "",
   "source_url": "https://commons.wikimedia.org/wiki/File:Big-sur.webm",
   "generator": "OpenAI Sora (2024)",
   "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly.",
   "has_audio": ""
  }
 ]
];
window.ITEMS = window.ROUNDS.flat();
