// 24 items: answer, tell and credits. Source: pamokos-vaikams/tikra-ar-ai/manifest.json
window.ITEMS = [
 {
  "file": "media/01-sesi-pirstai.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Suskaičiuok pirštus: jų šeši! Dirbtinis intelektas dažnai klysta piešdamas rankas.",
  "author": "Stable Diffusion 1.5, prompted by Corvus",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:AI_generated_hand.png",
  "generator": "Stable Diffusion 1.5",
  "note": ""
 },
 {
  "file": "media/02-melynas-omaras.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Maždaug vienas omaras iš dviejų milijonų gimsta mėlynas.",
  "author": "EgorovaSvetlana",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Blue_Lobster_Woods_Hole_Science_Aquarium.jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/03-rozinis-ezeras.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Šis ežeras Australijoje rožinis dėl mažyčių dumblių ir druskos.",
  "author": "Aussie Oc",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Lake_Hillier_2_Middle_Island_Recherche_Archipelago_NR_IV-2011.JPG",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/04-mamutai.mp4",
  "answer": "ai",
  "kind": "video",
  "tell_lt": "Mamutai išnyko prieš tūkstančius metų. Niekas negalėjo jų nufilmuoti.",
  "author": "Sora / OpenAI",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Wooly_Mammoth_by_OpenAI_Sora.webm",
  "generator": "OpenAI Sora (2024)",
  "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly."
 },
 {
  "file": "media/05-lemuras-kompiuteris.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Lemūrai nemoka naudotis kompiuteriu. Ekrane ne raidės, o raibuliai.",
  "author": "Image Creator by Microsoft Bing",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:A_lemur_editing_Wikipedia_08.jpg",
  "generator": "Microsoft Bing Image Creator (DALL-E 3)",
  "note": ""
 },
 {
  "file": "media/06-juru-sliuzas-sokeja.mp4",
  "answer": "real",
  "kind": "video",
  "tell_lt": "Tikras! Tai jūrų šliužas, vadinamas ispanų šokėja. Jis tikrai taip plaukia.",
  "author": "Christopher Rabotin",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Spanish_dancer_nudibranch.webm",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/07-kaciukas-ir-ancius.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Ančiukų snapai ir kojos atrodo kaip rožinis plastikas.",
  "author": "matankic",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Ducklings_and_kittens_play_super_cute_high_resulotion.png",
  "generator": "DALL-E (2022), vėliau taisyta GIMP",
  "note": ""
 },
 {
  "file": "media/08-druskos-veidrodis.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Bolivijoje yra didžiulė druskos lyguma. Po lietaus ji tampa veidrodžiu.",
  "author": "Luca Galuzzi (Lucag)",
  "license": "CC BY-SA 2.5",
  "license_url": "https://creativecommons.org/licenses/by-sa/2.5",
  "source_url": "https://commons.wikimedia.org/wiki/File:Watching_Sunset_Salar_de_Uyuni_Bolivia_Luca_Galuzzi_2006.jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/09-katinas-lovoje.mp4",
  "answer": "ai",
  "kind": "video",
  "tell_lt": "Stebėk katino letenas. Viena letena staiga atsiranda iš niekur.",
  "author": "Sora/OpenAI",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Cat-on-bed.webm",
  "generator": "OpenAI Sora (2024)",
  "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly."
 },
 {
  "file": "media/10-levandu-ledai.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Viskas per tobula. Visi rutuliai vienodi, o žiedeliai išdėlioti lyg ranka.",
  "author": "SNRTZ",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Levendul%C3%A1s_fagylalt.png",
  "generator": "nežinomas (įkėlėjas pažymėjo kaip AI)",
  "note": ""
 },
 {
  "file": "media/11-varnenu-debesis.mp4",
  "answer": "real",
  "kind": "video",
  "tell_lt": "Tikras! Tūkstančiai varnėnų skrenda kartu ir sukuria judantį debesį.",
  "author": "Karen Roe",
  "license": "CC BY 2.0",
  "license_url": "https://creativecommons.org/licenses/by/2.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Flock_of_starlings_(Sturnus_vulgaris).webm",
  "generator": "",
  "note": "Cut from the Commons 1080p transcode, 12-23 s."
 },
 {
  "file": "media/12-vezys-dalgininkas.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Vėžys dalgininkas mato daugiau spalvų nei žmogus.",
  "author": "Jens Petersen",
  "license": "CC BY 2.5",
  "license_url": "https://creativecommons.org/licenses/by/2.5",
  "source_url": "https://commons.wikimedia.org/wiki/File:Odontodactylus_scyllarus1.jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/13-meska-geles.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Gėlės aplink mešką sudėliotos per gražiai. Kailis atrodo lyg nupieštas teptuku.",
  "author": "Kandukuru Nagarjun from Bangalore, India",
  "license": "CC BY 2.0",
  "license_url": "https://creativecommons.org/licenses/by/2.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:An_Asian_black_bear_amidst_mahua_flowers_(52842957476).png",
  "generator": "Midjourney (2023)",
  "note": ""
 },
 {
  "file": "media/14-vaivorykstinis-eukaliptas.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Šio medžio žievė lupasi, o po ja matosi žalia, oranžinė ir violetinė.",
  "author": "Forest and Kim Starr",
  "license": "CC BY 3.0 us",
  "license_url": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
  "source_url": "https://commons.wikimedia.org/wiki/File:Starr-090618-1062-Eucalyptus_deglupta-trunk_and_bark-Hana_Hwy-Maui_(24670004300).jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/15-kalnai-is-virsaus.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Labai sunku! Pažiūrėk į keistą ilgą spindulį, krentantį nuo saulės žemyn.",
  "author": "Adobe Firefly Image 3, prompted by Jiří Vedral",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Adobe_Firefly_generated_landscape_photography.jpg",
  "generator": "Adobe Firefly Image 3",
  "note": ""
 },
 {
  "file": "media/16-sepija.mp4",
  "answer": "real",
  "kind": "video",
  "tell_lt": "Tikras! Puošnioji sepija gali per akimirką pakeisti odos spalvą ir raštą.",
  "author": "Sgerbic",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Flamboyant_cuttlefish_neutral_palette.webm",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/17-uolu-pakrante.mp4",
  "answer": "ai",
  "kind": "video",
  "tell_lt": "Labai sunku! Šį vaizdą sukūrė Sora iš vieno sakinio, o ne dronas.",
  "author": "Sora/OpenAI",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Big-sur.webm",
  "generator": "OpenAI Sora (2024)",
  "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly."
 },
 {
  "file": "media/18-lapuotasis-juru-drakonas.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Lapuotasis jūrų drakonas yra jūrų arkliuko giminaitis. Jis slepiasi tarp dumblių.",
  "author": "Photo by and (C)2007 Derek Ramsey (Ram-Man)",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Leafy_Seadragon_Phycodurus_eques_2500px.jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/19-zalias-obuolys.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Beveik neįmanoma atskirti! Net paprastas obuolys gali būti netikras.",
  "author": "Midjourney; prompted by The masketta man",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Green_apple_gen.png",
  "generator": "Midjourney v6",
  "note": ""
 },
 {
  "file": "media/20-romaninis-brokolis.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Šis brokolis sudarytas iš bokštelių, kurie kartojasi vis mažesni.",
  "author": "Richard Bartz, Munich aka Makro Freak",
  "license": "CC BY-SA 2.5",
  "license_url": "https://creativecommons.org/licenses/by-sa/2.5",
  "source_url": "https://commons.wikimedia.org/wiki/File:Romanesco_Brassica_oleracea_Richard_Bartz.jpg",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/21-zalia-varle-zuvis.mp4",
  "answer": "real",
  "kind": "video",
  "tell_lt": "Tikras! Žuvis varlė apsimeta kempine, kad grobis jos nepastebėtų.",
  "author": "Marwan Mohamad",
  "license": "CC BY-SA 4.0",
  "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
  "source_url": "https://commons.wikimedia.org/wiki/File:Giant_Frogfish_(Antennarius_commerson)_in_Bangka_Island,_North_Sulawesi,_Indonesia.webm",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/22-slenis-su-nameliu.jpg",
  "answer": "ai",
  "kind": "image",
  "tell_lt": "Sunku! Pažiūrėk į akmenis upėje. Jie išrikiuoti per tvarkingai.",
  "author": "VulcanSphere",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Illuminated_Valley_in_the_Afternoon_(Imagen_4.0).webp",
  "generator": "Google Imagen 4.0 (Gemini)",
  "note": "Bottom-right Gemini watermark cropped out."
 },
 {
  "file": "media/23-tesmeniniai-debesys.jpg",
  "answer": "real",
  "kind": "image",
  "tell_lt": "Tikras! Tokie gumuluoti debesys vadinami tešmeniniais. Jie kartais būna po audros.",
  "author": "NOAA",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Mammatus-clouds-Tulsa-1973.png",
  "generator": "",
  "note": ""
 },
 {
  "file": "media/24-karunuotasis-balandis.mp4",
  "answer": "ai",
  "kind": "video",
  "tell_lt": "Toks paukštis tikrai yra, tai karūnuotasis balandis. Bet šį filmuką sukūrė Sora.",
  "author": "Sora/OpenAI",
  "license": "Public domain",
  "license_url": "",
  "source_url": "https://commons.wikimedia.org/wiki/File:Victoria-crowned-pigeon.webm",
  "generator": "OpenAI Sora (2024)",
  "note": "Original from openai.com/sora (Feb 2024). Edges cropped slightly."
 }
];
